/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TimerType = IDL.Variant({
  'presale' : IDL.Null,
  'airdrop' : IDL.Null,
});
export const IndicatorType = IDL.Variant({
  'fvg' : IDL.Null,
  'rsi' : IDL.Null,
  'macd' : IDL.Null,
  'vwap' : IDL.Null,
  'movingAverage' : IDL.Null,
  'bollingerBands' : IDL.Null,
  'orderBlocks' : IDL.Null,
});
export const SignalConfidence = IDL.Variant({
  'buy' : IDL.Null,
  'strongBuy' : IDL.Null,
  'sell' : IDL.Null,
  'neutral' : IDL.Null,
  'strongSell' : IDL.Null,
});
export const TechnicalIndicator = IDL.Record({
  'value' : IDL.Float64,
  'indicatorType' : IndicatorType,
  'signal' : SignalConfidence,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'read' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MarketIntelligence = IDL.Record({
  'id' : IDL.Nat,
  'historicalAccuracy' : IDL.Float64,
  'asset' : IDL.Text,
  'timeframe' : IDL.Text,
  'overallSignal' : SignalConfidence,
  'indicators' : IDL.Vec(TechnicalIndicator),
  'timestamp' : IDL.Int,
});
export const FormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'country' : IDL.Text,
  'isPresale' : IDL.Bool,
  'name' : IDL.Text,
  'submittedBy' : IDL.Principal,
  'walletAddress' : IDL.Text,
  'rbsAmount' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const TimerState = IDL.Record({
  'endTime' : IDL.Int,
  'lastUpdate' : IDL.Int,
  'isUnlocked' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAlert' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkMarketIntelAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'clearAlerts' : IDL.Func([], [], []),
  'clearAllRecords' : IDL.Func([], [], []),
  'createRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteAlert' : IDL.Func([IDL.Nat], [], []),
  'deleteMarketIntelligence' : IDL.Func([IDL.Nat], [], []),
  'deleteRecord' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteSubmission' : IDL.Func([IDL.Nat], [], []),
  'deleteTimer' : IDL.Func([TimerType], [], []),
  'generateMarketIntel' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(TechnicalIndicator),
        SignalConfidence,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'getAirdropRemainingTime' : IDL.Func([], [IDL.Int], ['query']),
  'getAlertCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllMarketIntelligence' : IDL.Func(
      [],
      [IDL.Vec(MarketIntelligence)],
      ['query'],
    ),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(FormSubmission)], ['query']),
  'getAllTimers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, TimerState))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentId' : IDL.Func([], [IDL.Nat], ['query']),
  'getFormSubmission' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(FormSubmission)],
      ['query'],
    ),
  'getMarketIntelligence' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(MarketIntelligence)],
      ['query'],
    ),
  'getMarketIntelligenceByAsset' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MarketIntelligence)],
      ['query'],
    ),
  'getMarketIntelligenceByTimeframe' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MarketIntelligence)],
      ['query'],
    ),
  'getMarketIntelligenceByTimeframeAndAsset' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(MarketIntelligence)],
      ['query'],
    ),
  'getMarketIntelligenceCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getMySubmissions' : IDL.Func([], [IDL.Vec(FormSubmission)], ['query']),
  'getPresaleRemainingTime' : IDL.Func([], [IDL.Int], ['query']),
  'getRecordCounts' : IDL.Func(
      [],
      [
        IDL.Record({
          'roadmap' : IDL.Nat,
          'insights' : IDL.Nat,
          'contact' : IDL.Nat,
          'about' : IDL.Nat,
          'faqs' : IDL.Nat,
          'community' : IDL.Nat,
          'ecosystem' : IDL.Nat,
          'security' : IDL.Nat,
          'whitepaper' : IDL.Nat,
          'testimonials' : IDL.Nat,
          'governance' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getRecords' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getSubmissionsByCountry' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FormSubmission)],
      ['query'],
    ),
  'getSubmissionsByType' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(FormSubmission)],
      ['query'],
    ),
  'getSubmissionsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTimerState' : IDL.Func([TimerType], [IDL.Opt(TimerState)], ['query']),
  'getTimerStates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, TimerState))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantMarketIntelAccess' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'hasAISentimentAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAlertAsRead' : IDL.Func([IDL.Nat], [], []),
  'massDeleteAllSubmissions' : IDL.Func([], [], []),
  'massPopulateRecords' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'revokeMarketIntelAccessWithPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'toggleTimer' : IDL.Func([TimerType], [TimerState], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'updateSubmission' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
      [],
      [],
    ),
  'updateTimer' : IDL.Func([TimerType, IDL.Bool, IDL.Int], [TimerState], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TimerType = IDL.Variant({ 'presale' : IDL.Null, 'airdrop' : IDL.Null });
  const IndicatorType = IDL.Variant({
    'fvg' : IDL.Null,
    'rsi' : IDL.Null,
    'macd' : IDL.Null,
    'vwap' : IDL.Null,
    'movingAverage' : IDL.Null,
    'bollingerBands' : IDL.Null,
    'orderBlocks' : IDL.Null,
  });
  const SignalConfidence = IDL.Variant({
    'buy' : IDL.Null,
    'strongBuy' : IDL.Null,
    'sell' : IDL.Null,
    'neutral' : IDL.Null,
    'strongSell' : IDL.Null,
  });
  const TechnicalIndicator = IDL.Record({
    'value' : IDL.Float64,
    'indicatorType' : IndicatorType,
    'signal' : SignalConfidence,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'read' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const MarketIntelligence = IDL.Record({
    'id' : IDL.Nat,
    'historicalAccuracy' : IDL.Float64,
    'asset' : IDL.Text,
    'timeframe' : IDL.Text,
    'overallSignal' : SignalConfidence,
    'indicators' : IDL.Vec(TechnicalIndicator),
    'timestamp' : IDL.Int,
  });
  const FormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'country' : IDL.Text,
    'isPresale' : IDL.Bool,
    'name' : IDL.Text,
    'submittedBy' : IDL.Principal,
    'walletAddress' : IDL.Text,
    'rbsAmount' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const TimerState = IDL.Record({
    'endTime' : IDL.Int,
    'lastUpdate' : IDL.Int,
    'isUnlocked' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAlert' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkMarketIntelAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'clearAlerts' : IDL.Func([], [], []),
    'clearAllRecords' : IDL.Func([], [], []),
    'createRecord' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteAlert' : IDL.Func([IDL.Nat], [], []),
    'deleteMarketIntelligence' : IDL.Func([IDL.Nat], [], []),
    'deleteRecord' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteSubmission' : IDL.Func([IDL.Nat], [], []),
    'deleteTimer' : IDL.Func([TimerType], [], []),
    'generateMarketIntel' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(TechnicalIndicator),
          SignalConfidence,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'getAirdropRemainingTime' : IDL.Func([], [IDL.Int], ['query']),
    'getAlertCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllMarketIntelligence' : IDL.Func(
        [],
        [IDL.Vec(MarketIntelligence)],
        ['query'],
      ),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(FormSubmission)], ['query']),
    'getAllTimers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, TimerState))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentId' : IDL.Func([], [IDL.Nat], ['query']),
    'getFormSubmission' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(FormSubmission)],
        ['query'],
      ),
    'getMarketIntelligence' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(MarketIntelligence)],
        ['query'],
      ),
    'getMarketIntelligenceByAsset' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MarketIntelligence)],
        ['query'],
      ),
    'getMarketIntelligenceByTimeframe' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MarketIntelligence)],
        ['query'],
      ),
    'getMarketIntelligenceByTimeframeAndAsset' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(MarketIntelligence)],
        ['query'],
      ),
    'getMarketIntelligenceCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getMySubmissions' : IDL.Func([], [IDL.Vec(FormSubmission)], ['query']),
    'getPresaleRemainingTime' : IDL.Func([], [IDL.Int], ['query']),
    'getRecordCounts' : IDL.Func(
        [],
        [
          IDL.Record({
            'roadmap' : IDL.Nat,
            'insights' : IDL.Nat,
            'contact' : IDL.Nat,
            'about' : IDL.Nat,
            'faqs' : IDL.Nat,
            'community' : IDL.Nat,
            'ecosystem' : IDL.Nat,
            'security' : IDL.Nat,
            'whitepaper' : IDL.Nat,
            'testimonials' : IDL.Nat,
            'governance' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getRecords' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getSubmissionsByCountry' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FormSubmission)],
        ['query'],
      ),
    'getSubmissionsByType' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(FormSubmission)],
        ['query'],
      ),
    'getSubmissionsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTimerState' : IDL.Func([TimerType], [IDL.Opt(TimerState)], ['query']),
    'getTimerStates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, TimerState))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantMarketIntelAccess' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'hasAISentimentAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAlertAsRead' : IDL.Func([IDL.Nat], [], []),
    'massDeleteAllSubmissions' : IDL.Func([], [], []),
    'massPopulateRecords' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'revokeMarketIntelAccessWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'toggleTimer' : IDL.Func([TimerType], [TimerState], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'updateSubmission' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool],
        [],
        [],
      ),
    'updateTimer' : IDL.Func([TimerType, IDL.Bool, IDL.Int], [TimerState], []),
  });
};

export const init = ({ IDL }) => { return []; };