/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'read' : IDL.Bool,
  'triggerEnabled' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'lastChecked' : IDL.Int,
  'autoCreated' : IDL.Bool,
});
export const CreatePollInput = IDL.Record({
  'question' : IDL.Text,
  'code' : IDL.Text,
  'isActive' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const KeyVal = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Nat });
export const Time = IDL.Int;
export const PollView = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'question' : IDL.Text,
  'votes' : IDL.Vec(KeyVal),
  'code' : IDL.Text,
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'options' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const TimerType = IDL.Variant({
  'presale' : IDL.Null,
  'airdrop' : IDL.Null,
});
export const TimerState = IDL.Record({
  'endTime' : IDL.Int,
  'lastUpdate' : IDL.Int,
  'isUnlocked' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAndCreateAutoAlert' : IDL.Func([], [IDL.Opt(Alert)], []),
  'createAlert' : IDL.Func([IDL.Text, IDL.Text], [Alert], []),
  'createPoll' : IDL.Func([CreatePollInput], [IDL.Nat], []),
  'deleteAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'enableTrigger' : IDL.Func([IDL.Bool], [], []),
  'getAirdropRemainingTime' : IDL.Func([], [IDL.Int], ['query']),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllPolls' : IDL.Func([], [IDL.Vec(PollView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLastPoll' : IDL.Func([], [IDL.Opt(PollView)], ['query']),
  'getPoll' : IDL.Func([IDL.Nat], [IDL.Opt(PollView)], ['query']),
  'getPresaleRemainingTime' : IDL.Func([], [IDL.Int], ['query']),
  'getTimerState' : IDL.Func([TimerType], [TimerState], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantMarketIntelAccess' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'hasMarketIntelAccess' : IDL.Func([], [IDL.Bool], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAlertAsRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'revokeMarketIntelAccessWithPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitVote' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'toggleTimer' : IDL.Func([TimerType], [TimerState], []),
  'updateRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'vote' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'read' : IDL.Bool,
    'triggerEnabled' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'lastChecked' : IDL.Int,
    'autoCreated' : IDL.Bool,
  });
  const CreatePollInput = IDL.Record({
    'question' : IDL.Text,
    'code' : IDL.Text,
    'isActive' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const KeyVal = IDL.Record({ 'key' : IDL.Text, 'value' : IDL.Nat });
  const Time = IDL.Int;
  const PollView = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'question' : IDL.Text,
    'votes' : IDL.Vec(KeyVal),
    'code' : IDL.Text,
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'options' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const TimerType = IDL.Variant({ 'presale' : IDL.Null, 'airdrop' : IDL.Null });
  const TimerState = IDL.Record({
    'endTime' : IDL.Int,
    'lastUpdate' : IDL.Int,
    'isUnlocked' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAndCreateAutoAlert' : IDL.Func([], [IDL.Opt(Alert)], []),
    'createAlert' : IDL.Func([IDL.Text, IDL.Text], [Alert], []),
    'createPoll' : IDL.Func([CreatePollInput], [IDL.Nat], []),
    'deleteAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'enableTrigger' : IDL.Func([IDL.Bool], [], []),
    'getAirdropRemainingTime' : IDL.Func([], [IDL.Int], ['query']),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllPolls' : IDL.Func([], [IDL.Vec(PollView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLastPoll' : IDL.Func([], [IDL.Opt(PollView)], ['query']),
    'getPoll' : IDL.Func([IDL.Nat], [IDL.Opt(PollView)], ['query']),
    'getPresaleRemainingTime' : IDL.Func([], [IDL.Int], ['query']),
    'getTimerState' : IDL.Func([TimerType], [TimerState], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantMarketIntelAccess' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'hasMarketIntelAccess' : IDL.Func([], [IDL.Bool], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAlertAsRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'revokeMarketIntelAccessWithPassword' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitVote' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'toggleTimer' : IDL.Func([TimerType], [TimerState], []),
    'updateRecord' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'vote' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };