/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'title' : string,
  'read' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface FormSubmission {
  'id' : bigint,
  'country' : string,
  'isPresale' : boolean,
  'name' : string,
  'submittedBy' : Principal,
  'walletAddress' : string,
  'rbsAmount' : number,
  'timestamp' : bigint,
}
export type IndicatorType = { 'fvg' : null } |
  { 'rsi' : null } |
  { 'macd' : null } |
  { 'vwap' : null } |
  { 'movingAverage' : null } |
  { 'bollingerBands' : null } |
  { 'orderBlocks' : null };
export interface MarketIntelligence {
  'id' : bigint,
  'historicalAccuracy' : number,
  'asset' : string,
  'timeframe' : string,
  'overallSignal' : SignalConfidence,
  'indicators' : Array<TechnicalIndicator>,
  'timestamp' : bigint,
}
export type SignalConfidence = { 'buy' : null } |
  { 'strongBuy' : null } |
  { 'sell' : null } |
  { 'neutral' : null } |
  { 'strongSell' : null };
export interface TechnicalIndicator {
  'value' : number,
  'indicatorType' : IndicatorType,
  'signal' : SignalConfidence,
}
export interface TimerState {
  'endTime' : bigint,
  'lastUpdate' : bigint,
  'isUnlocked' : boolean,
}
export type TimerType = { 'presale' : null } |
  { 'airdrop' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAlert' : ActorMethod<[string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkMarketIntelAccess' : ActorMethod<[], boolean>,
  'clearAlerts' : ActorMethod<[], undefined>,
  'clearAllRecords' : ActorMethod<[], undefined>,
  'createRecord' : ActorMethod<[string, string], bigint>,
  'deleteAlert' : ActorMethod<[bigint], undefined>,
  'deleteMarketIntelligence' : ActorMethod<[bigint], undefined>,
  'deleteRecord' : ActorMethod<[string, bigint], undefined>,
  'deleteSubmission' : ActorMethod<[bigint], undefined>,
  'deleteTimer' : ActorMethod<[TimerType], undefined>,
  'generateMarketIntel' : ActorMethod<
    [string, string, Array<TechnicalIndicator>, SignalConfidence, number],
    bigint
  >,
  'getAirdropRemainingTime' : ActorMethod<[], bigint>,
  'getAlertCount' : ActorMethod<[], bigint>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllMarketIntelligence' : ActorMethod<[], Array<MarketIntelligence>>,
  'getAllSubmissions' : ActorMethod<[], Array<FormSubmission>>,
  'getAllTimers' : ActorMethod<[], Array<[string, TimerState]>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentId' : ActorMethod<[], bigint>,
  'getFormSubmission' : ActorMethod<[bigint], [] | [FormSubmission]>,
  'getMarketIntelligence' : ActorMethod<[bigint], [] | [MarketIntelligence]>,
  'getMarketIntelligenceByAsset' : ActorMethod<
    [string],
    Array<MarketIntelligence>
  >,
  'getMarketIntelligenceByTimeframe' : ActorMethod<
    [string],
    Array<MarketIntelligence>
  >,
  'getMarketIntelligenceByTimeframeAndAsset' : ActorMethod<
    [string, string],
    Array<MarketIntelligence>
  >,
  'getMarketIntelligenceCount' : ActorMethod<[], bigint>,
  'getMySubmissions' : ActorMethod<[], Array<FormSubmission>>,
  'getPresaleRemainingTime' : ActorMethod<[], bigint>,
  'getRecordCounts' : ActorMethod<
    [],
    {
      'roadmap' : bigint,
      'insights' : bigint,
      'contact' : bigint,
      'about' : bigint,
      'faqs' : bigint,
      'community' : bigint,
      'ecosystem' : bigint,
      'security' : bigint,
      'whitepaper' : bigint,
      'testimonials' : bigint,
      'governance' : bigint,
    }
  >,
  'getRecords' : ActorMethod<[string], Array<string>>,
  'getSubmissionsByCountry' : ActorMethod<[string], Array<FormSubmission>>,
  'getSubmissionsByType' : ActorMethod<[boolean], Array<FormSubmission>>,
  'getSubmissionsCount' : ActorMethod<[], bigint>,
  'getTimerState' : ActorMethod<[TimerType], [] | [TimerState]>,
  'getTimerStates' : ActorMethod<[], Array<[string, TimerState]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantMarketIntelAccess' : ActorMethod<[string], boolean>,
  'hasAISentimentAccess' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAlertAsRead' : ActorMethod<[bigint], undefined>,
  'massDeleteAllSubmissions' : ActorMethod<[], undefined>,
  'massPopulateRecords' : ActorMethod<[string, Array<string>], undefined>,
  'revokeMarketIntelAccessWithPassword' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitForm' : ActorMethod<[string, string, string, number, boolean], bigint>,
  'toggleTimer' : ActorMethod<[TimerType], TimerState>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateRecord' : ActorMethod<[string, bigint, string], undefined>,
  'updateSubmission' : ActorMethod<
    [bigint, string, string, string, number, boolean],
    undefined
  >,
  'updateTimer' : ActorMethod<[TimerType, boolean, bigint], TimerState>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];