/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'title' : string,
  'read' : boolean,
  'triggerEnabled' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'lastChecked' : bigint,
  'autoCreated' : boolean,
}
export interface CreatePollInput {
  'question' : string,
  'code' : string,
  'isActive' : boolean,
  'options' : Array<string>,
}
export interface KeyVal { 'key' : string, 'value' : bigint }
export interface PollView {
  'id' : bigint,
  'creator' : Principal,
  'question' : string,
  'votes' : Array<KeyVal>,
  'code' : string,
  'createdAt' : Time,
  'isActive' : boolean,
  'options' : Array<string>,
}
export type Time = bigint;
export interface TimerState {
  'endTime' : bigint,
  'lastUpdate' : bigint,
  'isUnlocked' : boolean,
}
export type TimerType = { 'presale' : null } |
  { 'airdrop' : null };
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndCreateAutoAlert' : ActorMethod<[], [] | [Alert]>,
  'createAlert' : ActorMethod<[string, string], Alert>,
  'createPoll' : ActorMethod<[CreatePollInput], bigint>,
  'deleteAlert' : ActorMethod<[bigint], boolean>,
  'enableTrigger' : ActorMethod<[boolean], undefined>,
  'getAirdropRemainingTime' : ActorMethod<[], bigint>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllPolls' : ActorMethod<[], Array<PollView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLastPoll' : ActorMethod<[], [] | [PollView]>,
  'getPoll' : ActorMethod<[bigint], [] | [PollView]>,
  'getPresaleRemainingTime' : ActorMethod<[], bigint>,
  'getTimerState' : ActorMethod<[TimerType], TimerState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantMarketIntelAccess' : ActorMethod<[string], boolean>,
  'hasMarketIntelAccess' : ActorMethod<[], boolean>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAlertAsRead' : ActorMethod<[bigint], boolean>,
  'revokeMarketIntelAccessWithPassword' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitVote' : ActorMethod<[bigint, bigint], boolean>,
  'toggleTimer' : ActorMethod<[TimerType], TimerState>,
  'updateRecord' : ActorMethod<[string, bigint, string], undefined>,
  'vote' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];