/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'title' : string,
  'read' : boolean,
  'triggerEnabled' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'lastChecked' : bigint,
  'autoCreated' : boolean,
}
export interface CreatePollInput {
  'question' : string,
  'code' : string,
  'isActive' : boolean,
  'options' : Array<string>,
}
export interface CryptoCurrency {
  'lastUpdateTimestamp' : bigint,
  'currentPriceUsd' : number,
  'symbol' : string,
  'updateIntervalSecs' : bigint,
}
export interface FormSubmission {
  'id' : bigint,
  'country' : string,
  'isPresale' : boolean,
  'name' : string,
  'submittedBy' : Principal,
  'walletAddress' : string,
  'rbsAmount' : number,
  'timestamp' : bigint,
}
export type IndicatorType = { 'fvg' : null } |
  { 'rsi' : null } |
  { 'macd' : null } |
  { 'vwap' : null } |
  { 'movingAverage' : null } |
  { 'bollingerBands' : null } |
  { 'orderBlocks' : null };
export interface KeyVal { 'key' : string, 'value' : bigint }
export interface MarketIntelligence {
  'id' : bigint,
  'historicalAccuracy' : number,
  'asset' : string,
  'timeframe' : string,
  'overallSignal' : SignalConfidence,
  'indicators' : Array<TechnicalIndicator>,
  'timestamp' : bigint,
}
export interface PollView {
  'id' : bigint,
  'creator' : Principal,
  'question' : string,
  'votes' : Array<KeyVal>,
  'code' : string,
  'createdAt' : Time,
  'isActive' : boolean,
  'options' : Array<string>,
}
export interface ScheduledTask {
  'name' : string,
  'lastRunTimestamp' : bigint,
  'intervalSeconds' : bigint,
}
export type SignalConfidence = { 'buy' : null } |
  { 'strongBuy' : null } |
  { 'sell' : null } |
  { 'neutral' : null } |
  { 'strongSell' : null };
export interface TechnicalIndicator {
  'value' : number,
  'indicatorType' : IndicatorType,
  'signal' : SignalConfidence,
}
export type Time = bigint;
export interface TimerState {
  'endTime' : bigint,
  'lastUpdate' : bigint,
  'isUnlocked' : boolean,
}
export type TimerType = { 'presale' : null } |
  { 'airdrop' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAndCreateAutoAlert' : ActorMethod<[], [] | [Alert]>,
  'createAlert' : ActorMethod<[string, string], Alert>,
  'createPoll' : ActorMethod<[CreatePollInput], bigint>,
  'deleteAlert' : ActorMethod<[bigint], boolean>,
  'enableTrigger' : ActorMethod<[boolean], undefined>,
  'getAirdropRemainingTime' : ActorMethod<[], bigint>,
  'getAirdropTimerEnd' : ActorMethod<[], bigint>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllCryptoCurrencies' : ActorMethod<[], Array<CryptoCurrency>>,
  'getAllMarketIntelligence' : ActorMethod<[], Array<MarketIntelligence>>,
  'getAllPolls' : ActorMethod<[], Array<PollView>>,
  'getAllSubmissions' : ActorMethod<[], Array<FormSubmission>>,
  'getBTCPriceFromCoingecko' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCryptoCurrency' : ActorMethod<[string], [] | [CryptoCurrency]>,
  'getLastPoll' : ActorMethod<[], [] | [PollView]>,
  'getMarketIntelligence' : ActorMethod<[bigint], [] | [MarketIntelligence]>,
  'getMySubmissions' : ActorMethod<[], Array<FormSubmission>>,
  'getPoll' : ActorMethod<[bigint], [] | [PollView]>,
  'getPollsByCode' : ActorMethod<[string], Array<PollView>>,
  'getPresaleRemainingTime' : ActorMethod<[], bigint>,
  'getPresaleTimerEnd' : ActorMethod<[], bigint>,
  'getScheduledTasks' : ActorMethod<[], Array<ScheduledTask>>,
  'getTimerState' : ActorMethod<[TimerType], TimerState>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantMarketIntelAccess' : ActorMethod<[string], boolean>,
  'hasMarketIntelAccess' : ActorMethod<[], boolean>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAlertAsRead' : ActorMethod<[bigint], boolean>,
  'revokeMarketIntelAccessWithPassword' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTimerEnd' : ActorMethod<[TimerType, bigint], undefined>,
  'storeMarketIntelligence' : ActorMethod<
    [string, string, Array<TechnicalIndicator>, SignalConfidence, number],
    MarketIntelligence
  >,
  'submitAirdropForm' : ActorMethod<
    [string, string, string, number],
    FormSubmission
  >,
  'submitPresaleForm' : ActorMethod<
    [string, string, string, number],
    FormSubmission
  >,
  'submitVote' : ActorMethod<[bigint, bigint], boolean>,
  'toggleAlertTrigger' : ActorMethod<[bigint], boolean>,
  'toggleTimer' : ActorMethod<[TimerType], TimerState>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateCryptoCurrency' : ActorMethod<[string, number, bigint], undefined>,
  'updateRecord' : ActorMethod<[string, bigint, string], undefined>,
  'vote' : ActorMethod<[bigint, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];