/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UserProfileEntry {
    principal: Principal;
    registeredAt?: bigint;
    profile: UserProfile;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface SignalConfidence {
    signal: Signal;
    confidence: bigint;
}
export interface PollView {
    id: bigint;
    creator: Principal;
    question: string;
    votes: Array<KeyVal>;
    code: string;
    createdAt: Time;
    isActive: boolean;
    options: Array<string>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ScheduledTask {
    name: string;
    lastRunTimestamp: bigint;
    intervalSeconds: bigint;
}
export interface MarketIntelligence {
    id: bigint;
    historicalAccuracy: number;
    asset: string;
    timeframe: string;
    overallSignal: SignalConfidence;
    indicators: Array<TechnicalIndicator>;
    timestamp: bigint;
}
export interface Alert {
    id: bigint;
    title: string;
    read: boolean;
    triggerEnabled: boolean;
    message: string;
    timestamp: bigint;
    lastChecked: bigint;
    autoCreated: boolean;
}
export interface CreatePollInput {
    question: string;
    code: string;
    isActive: boolean;
    options: Array<string>;
}
export interface BlogPost {
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    createdAt: bigint;
    tags: Array<string>;
    author: string;
    updatedAt?: bigint;
    category: string;
}
export interface TimerState {
    endTime: bigint;
    lastUpdate: bigint;
    isUnlocked: boolean;
}
export interface CryptoCurrency {
    lastUpdateTimestamp: bigint;
    currentPriceUsd: number;
    symbol: string;
    updateIntervalSecs: bigint;
}
export interface VoteTally {
    total: bigint;
    bullish: bigint;
    bearish: bigint;
    lastVoted?: MarketPulseVote;
    neutral: bigint;
}
export interface FormSubmission {
    id: bigint;
    country: string;
    isPresale: boolean;
    name: string;
    submittedBy: Principal;
    walletAddress: string;
    rbsAmount: number;
    timestamp: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TechnicalIndicator {
    value: number;
    indicatorType: IndicatorType;
    signal: SignalConfidence;
}
export interface KeyVal {
    key: string;
    value: bigint;
}
export interface UserProfile {
    username: string;
    displayName: string;
    email?: string;
    avatarUrl?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum IndicatorType {
    fvg = "fvg",
    rsi = "rsi",
    macd = "macd",
    vwap = "vwap",
    movingAverage = "movingAverage",
    bollingerBands = "bollingerBands",
    orderBlocks = "orderBlocks"
}
export enum MarketPulseVote {
    bullish = "bullish",
    bearish = "bearish",
    neutral = "neutral"
}
export enum Signal {
    buy = "buy",
    strongBuy = "strongBuy",
    sell = "sell",
    neutral = "neutral",
    strongSell = "strongSell"
}
export enum TimerType {
    presale = "presale",
    airdrop = "airdrop"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminGrantMarketIntelAccess(principal: Principal): Promise<boolean>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkAndCreateAutoAlert(): Promise<Alert | null>;
    createAlert(title: string, message: string): Promise<Alert>;
    createBlogPost(post: BlogPost, passcode: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createPoll(input: CreatePollInput): Promise<bigint>;
    deleteAlert(alertId: bigint): Promise<boolean>;
    deleteBlogPost(id: bigint, authorCode: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deletePoll(pollId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deletePollWithPasscode(pollId: bigint, passcode: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    enableTrigger(enable: boolean): Promise<void>;
    getAirdropRemainingTime(): Promise<bigint>;
    getAirdropTimerEnd(): Promise<bigint>;
    getAlerts(): Promise<Array<Alert>>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllBlogPostsAdmin(): Promise<Array<BlogPost>>;
    getAllCryptoCurrencies(): Promise<Array<CryptoCurrency>>;
    getAllMarketIntelligence(): Promise<Array<MarketIntelligence>>;
    getAllPolls(): Promise<Array<PollView>>;
    getAllSubmissions(): Promise<Array<FormSubmission>>;
    getAllUserProfiles(): Promise<Array<UserProfileEntry>>;
    getBTCPriceFromCoingecko(): Promise<string>;
    getBlogPostById(id: bigint): Promise<BlogPost | null>;
    getCallerRegistrationDate(): Promise<bigint | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCryptoCurrency(symbol: string): Promise<CryptoCurrency | null>;
    getGlobalSectionLock(section: string): Promise<boolean>;
    getMarketIntelPasscode(): Promise<string>;
    getMarketIntelligence(id: bigint): Promise<MarketIntelligence | null>;
    getMarketPulseTally(): Promise<VoteTally>;
    getMySubmissions(): Promise<Array<FormSubmission>>;
    getPoll(id: bigint): Promise<PollView | null>;
    getPollsByCode(code: string): Promise<Array<PollView>>;
    getPresaleRemainingTime(): Promise<bigint>;
    getPresaleTimerEnd(): Promise<bigint>;
    getPublishedPosts(): Promise<Array<BlogPost>>;
    getScheduledTasks(): Promise<Array<ScheduledTask>>;
    getTimerState(timerType: TimerType): Promise<TimerState>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRegistrationDate(user: Principal): Promise<bigint | null>;
    grantMarketIntelAccess(password: string): Promise<boolean>;
    hasMarketIntelAccess(): Promise<boolean>;
    hasMarketIntelAccessCheck(principal: Principal): Promise<boolean>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isUsernameTaken(username: string): Promise<boolean>;
    getTotalUserCount(): Promise<bigint>;
    markAlertAsRead(alertId: bigint): Promise<boolean>;
    publishBlogPost(post: BlogPost, passcode: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    revokeMarketIntelAccessWithPassword(password: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setGlobalSectionLock(section: string, passcode: string, unlock: boolean): Promise<void>;
    setMarketIntelPasscode(newPasscode: string): Promise<void>;
    setTimerEnd(timerType: TimerType, endTime: bigint): Promise<void>;
    storeMarketIntelligence(asset: string, timeframe: string, indicators: Array<TechnicalIndicator>, overallSignal: SignalConfidence, historicalAccuracy: number): Promise<MarketIntelligence>;
    submitAirdropForm(name: string, country: string, walletAddress: string, rbsAmount: number): Promise<FormSubmission>;
    submitPresaleForm(name: string, country: string, walletAddress: string, rbsAmount: number): Promise<FormSubmission>;
    submitVote(pollId: bigint, optionIndex: bigint): Promise<boolean>;
    toggleAlertTrigger(alertId: bigint): Promise<boolean>;
    toggleGlobalSectionLock(section: string, passcode: string): Promise<boolean>;
    toggleTimer(timerType: TimerType): Promise<TimerState>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateCryptoCurrency(symbol: string, priceUsd: number, updateIntervalSecs: bigint): Promise<void>;
    updateRecord(recordType: string, id: bigint, content: string): Promise<void>;
    verifyMarketIntelPasscode(passcode: string): Promise<boolean>;
    vote(pollId: bigint, option: string): Promise<boolean>;
    voteMarketPulse(sentiment: string): Promise<VoteTally>;
}
import type { Alert as _Alert, BlogPost as _BlogPost, CryptoCurrency as _CryptoCurrency, IndicatorType as _IndicatorType, MarketIntelligence as _MarketIntelligence, MarketPulseVote as _MarketPulseVote, PollView as _PollView, Signal as _Signal, SignalConfidence as _SignalConfidence, TechnicalIndicator as _TechnicalIndicator, TimerType as _TimerType, UserProfile as _UserProfile, UserProfileEntry as _UserProfileEntry, UserRole as _UserRole, VoteTally as _VoteTally, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminGrantMarketIntelAccess(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGrantMarketIntelAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGrantMarketIntelAccess(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkAndCreateAutoAlert(): Promise<Alert | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndCreateAutoAlert();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndCreateAutoAlert();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAlert(arg0: string, arg1: string): Promise<Alert> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(arg0, arg1);
            return result;
        }
    }
    async createBlogPost(arg0: BlogPost, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPoll(arg0: CreatePollInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPoll(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPoll(arg0);
            return result;
        }
    }
    async deleteAlert(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlert(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0, arg1);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0, arg1);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePoll(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePoll(arg0);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePoll(arg0);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePollWithPasscode(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePollWithPasscode(arg0, arg1);
                return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePollWithPasscode(arg0, arg1);
            return from_candid_variant_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async enableTrigger(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.enableTrigger(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enableTrigger(arg0);
            return result;
        }
    }
    async getAirdropRemainingTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAirdropRemainingTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAirdropRemainingTime();
            return result;
        }
    }
    async getAirdropTimerEnd(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAirdropTimerEnd();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAirdropTimerEnd();
            return result;
        }
    }
    async getAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlerts();
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBlogPostsAdmin(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPostsAdmin();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPostsAdmin();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCryptoCurrencies(): Promise<Array<CryptoCurrency>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCryptoCurrencies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCryptoCurrencies();
            return result;
        }
    }
    async getAllMarketIntelligence(): Promise<Array<MarketIntelligence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarketIntelligence();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarketIntelligence();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPolls(): Promise<Array<PollView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPolls();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPolls();
            return result;
        }
    }
    async getAllSubmissions(): Promise<Array<FormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return result;
        }
    }
    async getAllUserProfiles(): Promise<Array<UserProfileEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBTCPriceFromCoingecko(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBTCPriceFromCoingecko();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBTCPriceFromCoingecko();
            return result;
        }
    }
    async getBlogPostById(arg0: bigint): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostById(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostById(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerRegistrationDate(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerRegistrationDate();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerRegistrationDate();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCryptoCurrency(arg0: string): Promise<CryptoCurrency | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCryptoCurrency(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCryptoCurrency(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGlobalSectionLock(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalSectionLock(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalSectionLock(arg0);
            return result;
        }
    }
    async getMarketIntelPasscode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketIntelPasscode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketIntelPasscode();
            return result;
        }
    }
    async getMarketIntelligence(arg0: bigint): Promise<MarketIntelligence | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketIntelligence(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketIntelligence(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketPulseTally(): Promise<VoteTally> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketPulseTally();
                return from_candid_VoteTally_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketPulseTally();
            return from_candid_VoteTally_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySubmissions(): Promise<Array<FormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmissions();
            return result;
        }
    }
    async getPoll(arg0: bigint): Promise<PollView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPoll(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPoll(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPollsByCode(arg0: string): Promise<Array<PollView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPollsByCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPollsByCode(arg0);
            return result;
        }
    }
    async getPresaleRemainingTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresaleRemainingTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresaleRemainingTime();
            return result;
        }
    }
    async getPresaleTimerEnd(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresaleTimerEnd();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresaleTimerEnd();
            return result;
        }
    }
    async getPublishedPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedPosts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedPosts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScheduledTasks(): Promise<Array<ScheduledTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScheduledTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScheduledTasks();
            return result;
        }
    }
    async getTimerState(arg0: TimerType): Promise<TimerState> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimerState(to_candid_TimerType_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimerState(to_candid_TimerType_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRegistrationDate(arg0: Principal): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRegistrationDate(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRegistrationDate(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantMarketIntelAccess(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.grantMarketIntelAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantMarketIntelAccess(arg0);
            return result;
        }
    }
    async hasMarketIntelAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasMarketIntelAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasMarketIntelAccess();
            return result;
        }
    }
    async hasMarketIntelAccessCheck(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasMarketIntelAccessCheck(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasMarketIntelAccessCheck(arg0);
            return result;
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isUsernameTaken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUsernameTaken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUsernameTaken(arg0);
            return result;
        }
    }
    async getTotalUserCount(): Promise<bigint> {
        try {
            if (this.actor) {
                const result = await this.actor.getTotalUserCount();
                return result;
            }
        } catch (e) {
            return BigInt(0);
        }
        return BigInt(0);
    }

    async markAlertAsRead(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markAlertAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAlertAsRead(arg0);
            return result;
        }
    }
    async publishBlogPost(arg0: BlogPost, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.publishBlogPost(to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishBlogPost(to_candid_BlogPost_n11(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async revokeMarketIntelAccessWithPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeMarketIntelAccessWithPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeMarketIntelAccessWithPassword(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n51(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setGlobalSectionLock(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setGlobalSectionLock(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setGlobalSectionLock(arg0, arg1, arg2);
            return result;
        }
    }
    async setMarketIntelPasscode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMarketIntelPasscode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMarketIntelPasscode(arg0);
            return result;
        }
    }
    async setTimerEnd(arg0: TimerType, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTimerEnd(to_candid_TimerType_n49(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTimerEnd(to_candid_TimerType_n49(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async storeMarketIntelligence(arg0: string, arg1: string, arg2: Array<TechnicalIndicator>, arg3: SignalConfidence, arg4: number): Promise<MarketIntelligence> {
        if (this.processError) {
            try {
                const result = await this.actor.storeMarketIntelligence(arg0, arg1, to_candid_vec_n53(this._uploadFile, this._downloadFile, arg2), to_candid_SignalConfidence_n58(this._uploadFile, this._downloadFile, arg3), arg4);
                return from_candid_MarketIntelligence_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storeMarketIntelligence(arg0, arg1, to_candid_vec_n53(this._uploadFile, this._downloadFile, arg2), to_candid_SignalConfidence_n58(this._uploadFile, this._downloadFile, arg3), arg4);
            return from_candid_MarketIntelligence_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitAirdropForm(arg0: string, arg1: string, arg2: string, arg3: number): Promise<FormSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitAirdropForm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitAirdropForm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitPresaleForm(arg0: string, arg1: string, arg2: string, arg3: number): Promise<FormSubmission> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPresaleForm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPresaleForm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitVote(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVote(arg0, arg1);
            return result;
        }
    }
    async toggleAlertTrigger(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAlertTrigger(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAlertTrigger(arg0);
            return result;
        }
    }
    async toggleGlobalSectionLock(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleGlobalSectionLock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleGlobalSectionLock(arg0, arg1);
            return result;
        }
    }
    async toggleTimer(arg0: TimerType): Promise<TimerState> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTimer(to_candid_TimerType_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTimer(to_candid_TimerType_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateCryptoCurrency(arg0: string, arg1: number, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCryptoCurrency(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCryptoCurrency(arg0, arg1, arg2);
            return result;
        }
    }
    async updateRecord(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyMarketIntelPasscode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyMarketIntelPasscode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyMarketIntelPasscode(arg0);
            return result;
        }
    }
    async vote(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.vote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.vote(arg0, arg1);
            return result;
        }
    }
    async voteMarketPulse(arg0: string): Promise<VoteTally> {
        if (this.processError) {
            try {
                const result = await this.actor.voteMarketPulse(arg0);
                return from_candid_VoteTally_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteMarketPulse(arg0);
            return from_candid_VoteTally_n43(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BlogPost_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): BlogPost {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_IndicatorType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IndicatorType): IndicatorType {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_MarketIntelligence_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketIntelligence): MarketIntelligence {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_MarketPulseVote_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketPulseVote): MarketPulseVote {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_SignalConfidence_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalConfidence): SignalConfidence {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Signal_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Signal): Signal {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_TechnicalIndicator_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TechnicalIndicator): TechnicalIndicator {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfileEntry_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfileEntry): UserProfileEntry {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_VoteTally_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VoteTally): VoteTally {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Alert]): Alert | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : from_candid_BlogPost_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CryptoCurrency]): CryptoCurrency | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketIntelligence]): MarketIntelligence | null {
    return value.length === 0 ? null : from_candid_MarketIntelligence_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketPulseVote]): MarketPulseVote | null {
    return value.length === 0 ? null : from_candid_MarketPulseVote_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PollView]): PollView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    createdAt: bigint;
    tags: Array<string>;
    author: string;
    updatedAt: [] | [bigint];
    category: string;
}): {
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    createdAt: bigint;
    tags: Array<string>;
    author: string;
    updatedAt?: bigint;
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        isPublished: value.isPublished,
        body: value.body,
        createdAt: value.createdAt,
        tags: value.tags,
        author: value.author,
        updatedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.updatedAt)),
        category: value.category
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    historicalAccuracy: number;
    asset: string;
    timeframe: string;
    overallSignal: _SignalConfidence;
    indicators: Array<_TechnicalIndicator>;
    timestamp: bigint;
}): {
    id: bigint;
    historicalAccuracy: number;
    asset: string;
    timeframe: string;
    overallSignal: SignalConfidence;
    indicators: Array<TechnicalIndicator>;
    timestamp: bigint;
} {
    return {
        id: value.id,
        historicalAccuracy: value.historicalAccuracy,
        asset: value.asset,
        timeframe: value.timeframe,
        overallSignal: from_candid_SignalConfidence_n22(_uploadFile, _downloadFile, value.overallSignal),
        indicators: from_candid_vec_n26(_uploadFile, _downloadFile, value.indicators),
        timestamp: value.timestamp
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    signal: _Signal;
    confidence: bigint;
}): {
    signal: Signal;
    confidence: bigint;
} {
    return {
        signal: from_candid_Signal_n24(_uploadFile, _downloadFile, value.signal),
        confidence: value.confidence
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: number;
    indicatorType: _IndicatorType;
    signal: _SignalConfidence;
}): {
    value: number;
    indicatorType: IndicatorType;
    signal: SignalConfidence;
} {
    return {
        value: value.value,
        indicatorType: from_candid_IndicatorType_n29(_uploadFile, _downloadFile, value.indicatorType),
        signal: from_candid_SignalConfidence_n22(_uploadFile, _downloadFile, value.signal)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    registeredAt: [] | [bigint];
    profile: _UserProfile;
}): {
    principal: Principal;
    registeredAt?: bigint;
    profile: UserProfile;
} {
    return {
        principal: value.principal,
        registeredAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.registeredAt)),
        profile: from_candid_UserProfile_n34(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: string;
    email: [] | [string];
    avatarUrl: [] | [string];
}): {
    username: string;
    displayName: string;
    email?: string;
    avatarUrl?: string;
} {
    return {
        username: value.username,
        displayName: value.displayName,
        email: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.email)),
        avatarUrl: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    bullish: bigint;
    bearish: bigint;
    lastVoted: [] | [_MarketPulseVote];
    neutral: bigint;
}): {
    total: bigint;
    bullish: bigint;
    bearish: bigint;
    lastVoted?: MarketPulseVote;
    neutral: bigint;
} {
    return {
        total: value.total,
        bullish: value.bullish,
        bearish: value.bearish,
        lastVoted: record_opt_to_undefined(from_candid_opt_n45(_uploadFile, _downloadFile, value.lastVoted)),
        neutral: value.neutral
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    strongBuy: null;
} | {
    sell: null;
} | {
    neutral: null;
} | {
    strongSell: null;
}): Signal {
    return "buy" in value ? Signal.buy : "strongBuy" in value ? Signal.strongBuy : "sell" in value ? Signal.sell : "neutral" in value ? Signal.neutral : "strongSell" in value ? Signal.strongSell : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fvg: null;
} | {
    rsi: null;
} | {
    macd: null;
} | {
    vwap: null;
} | {
    movingAverage: null;
} | {
    bollingerBands: null;
} | {
    orderBlocks: null;
}): IndicatorType {
    return "fvg" in value ? IndicatorType.fvg : "rsi" in value ? IndicatorType.rsi : "macd" in value ? IndicatorType.macd : "vwap" in value ? IndicatorType.vwap : "movingAverage" in value ? IndicatorType.movingAverage : "bollingerBands" in value ? IndicatorType.bollingerBands : "orderBlocks" in value ? IndicatorType.orderBlocks : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bullish: null;
} | {
    bearish: null;
} | {
    neutral: null;
}): MarketPulseVote {
    return "bullish" in value ? MarketPulseVote.bullish : "bearish" in value ? MarketPulseVote.bearish : "neutral" in value ? MarketPulseVote.neutral : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Array<BlogPost> {
    return value.map((x)=>from_candid_BlogPost_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketIntelligence>): Array<MarketIntelligence> {
    return value.map((x)=>from_candid_MarketIntelligence_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TechnicalIndicator>): Array<TechnicalIndicator> {
    return value.map((x)=>from_candid_TechnicalIndicator_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfileEntry>): Array<UserProfileEntry> {
    return value.map((x)=>from_candid_UserProfileEntry_n32(_uploadFile, _downloadFile, x));
}
function to_candid_BlogPost_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPost): _BlogPost {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_IndicatorType_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndicatorType): _IndicatorType {
    return to_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function to_candid_SignalConfidence_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalConfidence): _SignalConfidence {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_Signal_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Signal): _Signal {
    return to_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function to_candid_TechnicalIndicator_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TechnicalIndicator): _TechnicalIndicator {
    return to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_TimerType_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimerType): _TimerType {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n52(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    createdAt: bigint;
    tags: Array<string>;
    author: string;
    updatedAt?: bigint;
    category: string;
}): {
    id: bigint;
    title: string;
    isPublished: boolean;
    body: string;
    createdAt: bigint;
    tags: Array<string>;
    author: string;
    updatedAt: [] | [bigint];
    category: string;
} {
    return {
        id: value.id,
        title: value.title,
        isPublished: value.isPublished,
        body: value.body,
        createdAt: value.createdAt,
        tags: value.tags,
        author: value.author,
        updatedAt: value.updatedAt ? candid_some(value.updatedAt) : candid_none(),
        category: value.category
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: string;
    email?: string;
    avatarUrl?: string;
}): {
    username: string;
    displayName: string;
    email: [] | [string];
    avatarUrl: [] | [string];
} {
    return {
        username: value.username,
        displayName: value.displayName,
        email: value.email ? candid_some(value.email) : candid_none(),
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none()
    };
}
function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: number;
    indicatorType: IndicatorType;
    signal: SignalConfidence;
}): {
    value: number;
    indicatorType: _IndicatorType;
    signal: _SignalConfidence;
} {
    return {
        value: value.value,
        indicatorType: to_candid_IndicatorType_n56(_uploadFile, _downloadFile, value.indicatorType),
        signal: to_candid_SignalConfidence_n58(_uploadFile, _downloadFile, value.signal)
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    signal: Signal;
    confidence: bigint;
}): {
    signal: _Signal;
    confidence: bigint;
} {
    return {
        signal: to_candid_Signal_n60(_uploadFile, _downloadFile, value.signal),
        confidence: value.confidence
    };
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimerType): {
    presale: null;
} | {
    airdrop: null;
} {
    return value == TimerType.presale ? {
        presale: null
    } : value == TimerType.airdrop ? {
        airdrop: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndicatorType): {
    fvg: null;
} | {
    rsi: null;
} | {
    macd: null;
} | {
    vwap: null;
} | {
    movingAverage: null;
} | {
    bollingerBands: null;
} | {
    orderBlocks: null;
} {
    return value == IndicatorType.fvg ? {
        fvg: null
    } : value == IndicatorType.rsi ? {
        rsi: null
    } : value == IndicatorType.macd ? {
        macd: null
    } : value == IndicatorType.vwap ? {
        vwap: null
    } : value == IndicatorType.movingAverage ? {
        movingAverage: null
    } : value == IndicatorType.bollingerBands ? {
        bollingerBands: null
    } : value == IndicatorType.orderBlocks ? {
        orderBlocks: null
    } : value;
}
function to_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Signal): {
    buy: null;
} | {
    strongBuy: null;
} | {
    sell: null;
} | {
    neutral: null;
} | {
    strongSell: null;
} {
    return value == Signal.buy ? {
        buy: null
    } : value == Signal.strongBuy ? {
        strongBuy: null
    } : value == Signal.sell ? {
        sell: null
    } : value == Signal.neutral ? {
        neutral: null
    } : value == Signal.strongSell ? {
        strongSell: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TechnicalIndicator>): Array<_TechnicalIndicator> {
    return value.map((x)=>to_candid_TechnicalIndicator_n54(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
