/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TimerState {
    endTime: bigint;
    lastUpdate: bigint;
    isUnlocked: boolean;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface FormSubmission {
    id: bigint;
    country: string;
    isPresale: boolean;
    name: string;
    submittedBy: Principal;
    walletAddress: string;
    rbsAmount: number;
    timestamp: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TechnicalIndicator {
    value: number;
    indicatorType: IndicatorType;
    signal: SignalConfidence;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface MarketIntelligence {
    id: bigint;
    historicalAccuracy: number;
    asset: string;
    timeframe: string;
    overallSignal: SignalConfidence;
    indicators: Array<TechnicalIndicator>;
    timestamp: bigint;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export enum IndicatorType {
    fvg = "fvg",
    rsi = "rsi",
    macd = "macd",
    vwap = "vwap",
    movingAverage = "movingAverage",
    bollingerBands = "bollingerBands",
    orderBlocks = "orderBlocks"
}
export enum SignalConfidence {
    buy = "buy",
    strongBuy = "strongBuy",
    sell = "sell",
    neutral = "neutral",
    strongSell = "strongSell"
}
export enum TimerType {
    presale = "presale",
    airdrop = "airdrop"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkMarketIntelAccess(): Promise<boolean>;
    clearAllRecords(): Promise<void>;
    createRecord(recordType: string, content: string): Promise<bigint>;
    deleteMarketIntelligence(id: bigint): Promise<void>;
    deleteRecord(recordType: string, id: bigint): Promise<void>;
    deleteSubmission(id: bigint): Promise<void>;
    deleteTimer(timerType: TimerType): Promise<void>;
    generateMarketIntel(asset: string, timeframe: string, indicators: Array<TechnicalIndicator>, overallSignal: SignalConfidence, historicalAccuracy: number): Promise<bigint>;
    getAirdropRemainingTime(): Promise<bigint>;
    getAllMarketIntelligence(): Promise<Array<MarketIntelligence>>;
    getAllSubmissions(): Promise<Array<FormSubmission>>;
    getAllTimers(): Promise<Array<[string, TimerState]>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentId(): Promise<bigint>;
    getFormSubmission(id: bigint): Promise<FormSubmission | null>;
    getMarketIntelligence(id: bigint): Promise<MarketIntelligence | null>;
    getMarketIntelligenceByAsset(asset: string): Promise<Array<MarketIntelligence>>;
    getMarketIntelligenceByTimeframe(timeframe: string): Promise<Array<MarketIntelligence>>;
    getMarketIntelligenceByTimeframeAndAsset(timeframe: string, asset: string): Promise<Array<MarketIntelligence>>;
    getMarketIntelligenceCount(): Promise<bigint>;
    getMySubmissions(): Promise<Array<FormSubmission>>;
    getPresaleRemainingTime(): Promise<bigint>;
    getRecordCounts(): Promise<{
        roadmap: bigint;
        insights: bigint;
        contact: bigint;
        about: bigint;
        faqs: bigint;
        community: bigint;
        ecosystem: bigint;
        security: bigint;
        whitepaper: bigint;
        testimonials: bigint;
        governance: bigint;
    }>;
    getRecords(recordType: string): Promise<Array<string>>;
    getSubmissionsByCountry(country: string): Promise<Array<FormSubmission>>;
    getSubmissionsByType(isPresale: boolean): Promise<Array<FormSubmission>>;
    getSubmissionsCount(): Promise<bigint>;
    getTimerState(timerType: TimerType): Promise<TimerState | null>;
    getTimerStates(): Promise<Array<[string, TimerState]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantMarketIntelAccess(password: string): Promise<boolean>;
    hasAISentimentAccess(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    massDeleteAllSubmissions(): Promise<void>;
    massPopulateRecords(recordType: string, contents: Array<string>): Promise<void>;
    revokeMarketIntelAccessWithPassword(password: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitForm(name: string, country: string, walletAddress: string, rbsAmount: number, isPresale: boolean): Promise<bigint>;
    toggleTimer(timerType: TimerType): Promise<TimerState>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateRecord(recordType: string, id: bigint, content: string): Promise<void>;
    updateSubmission(id: bigint, name: string, country: string, walletAddress: string, rbsAmount: number, isPresale: boolean): Promise<void>;
    updateTimer(timerType: TimerType, isUnlocked: boolean, endTime: bigint): Promise<TimerState>;
}
import type { FormSubmission as _FormSubmission, IndicatorType as _IndicatorType, MarketIntelligence as _MarketIntelligence, SignalConfidence as _SignalConfidence, TechnicalIndicator as _TechnicalIndicator, TimerState as _TimerState, TimerType as _TimerType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkMarketIntelAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkMarketIntelAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkMarketIntelAccess();
            return result;
        }
    }
    async clearAllRecords(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllRecords();
            return result;
        }
    }
    async createRecord(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecord(arg0, arg1);
            return result;
        }
    }
    async deleteMarketIntelligence(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMarketIntelligence(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMarketIntelligence(arg0);
            return result;
        }
    }
    async deleteRecord(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecord(arg0, arg1);
            return result;
        }
    }
    async deleteSubmission(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubmission(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubmission(arg0);
            return result;
        }
    }
    async deleteTimer(arg0: TimerType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTimer(to_candid_TimerType_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTimer(to_candid_TimerType_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateMarketIntel(arg0: string, arg1: string, arg2: Array<TechnicalIndicator>, arg3: SignalConfidence, arg4: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.generateMarketIntel(arg0, arg1, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2), to_candid_SignalConfidence_n17(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateMarketIntel(arg0, arg1, to_candid_vec_n12(this._uploadFile, this._downloadFile, arg2), to_candid_SignalConfidence_n17(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async getAirdropRemainingTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getAirdropRemainingTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAirdropRemainingTime();
            return result;
        }
    }
    async getAllMarketIntelligence(): Promise<Array<MarketIntelligence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarketIntelligence();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarketIntelligence();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubmissions(): Promise<Array<FormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubmissions();
            return result;
        }
    }
    async getAllTimers(): Promise<Array<[string, TimerState]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimers();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentId();
            return result;
        }
    }
    async getFormSubmission(arg0: bigint): Promise<FormSubmission | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFormSubmission(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFormSubmission(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketIntelligence(arg0: bigint): Promise<MarketIntelligence | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketIntelligence(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketIntelligence(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketIntelligenceByAsset(arg0: string): Promise<Array<MarketIntelligence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketIntelligenceByAsset(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketIntelligenceByAsset(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketIntelligenceByTimeframe(arg0: string): Promise<Array<MarketIntelligence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketIntelligenceByTimeframe(arg0);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketIntelligenceByTimeframe(arg0);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketIntelligenceByTimeframeAndAsset(arg0: string, arg1: string): Promise<Array<MarketIntelligence>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketIntelligenceByTimeframeAndAsset(arg0, arg1);
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketIntelligenceByTimeframeAndAsset(arg0, arg1);
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarketIntelligenceCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketIntelligenceCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketIntelligenceCount();
            return result;
        }
    }
    async getMySubmissions(): Promise<Array<FormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySubmissions();
            return result;
        }
    }
    async getPresaleRemainingTime(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPresaleRemainingTime();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPresaleRemainingTime();
            return result;
        }
    }
    async getRecordCounts(): Promise<{
        roadmap: bigint;
        insights: bigint;
        contact: bigint;
        about: bigint;
        faqs: bigint;
        community: bigint;
        ecosystem: bigint;
        security: bigint;
        whitepaper: bigint;
        testimonials: bigint;
        governance: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecordCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecordCounts();
            return result;
        }
    }
    async getRecords(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecords(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecords(arg0);
            return result;
        }
    }
    async getSubmissionsByCountry(arg0: string): Promise<Array<FormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByCountry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByCountry(arg0);
            return result;
        }
    }
    async getSubmissionsByType(arg0: boolean): Promise<Array<FormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsByType(arg0);
            return result;
        }
    }
    async getSubmissionsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubmissionsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubmissionsCount();
            return result;
        }
    }
    async getTimerState(arg0: TimerType): Promise<TimerState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimerState(to_candid_TimerType_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimerState(to_candid_TimerType_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimerStates(): Promise<Array<[string, TimerState]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimerStates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimerStates();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantMarketIntelAccess(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.grantMarketIntelAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantMarketIntelAccess(arg0);
            return result;
        }
    }
    async hasAISentimentAccess(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAISentimentAccess();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAISentimentAccess();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async massDeleteAllSubmissions(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.massDeleteAllSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.massDeleteAllSubmissions();
            return result;
        }
    }
    async massPopulateRecords(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.massPopulateRecords(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.massPopulateRecords(arg0, arg1);
            return result;
        }
    }
    async revokeMarketIntelAccessWithPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeMarketIntelAccessWithPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeMarketIntelAccessWithPassword(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitForm(arg0: string, arg1: string, arg2: string, arg3: number, arg4: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitForm(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitForm(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async toggleTimer(arg0: TimerType): Promise<TimerState> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTimer(to_candid_TimerType_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTimer(to_candid_TimerType_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateRecord(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async updateSubmission(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: number, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubmission(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubmission(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateTimer(arg0: TimerType, arg1: boolean, arg2: bigint): Promise<TimerState> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTimer(to_candid_TimerType_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTimer(to_candid_TimerType_n10(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
}
function from_candid_IndicatorType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IndicatorType): IndicatorType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MarketIntelligence_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketIntelligence): MarketIntelligence {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_SignalConfidence_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SignalConfidence): SignalConfidence {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TechnicalIndicator_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TechnicalIndicator): TechnicalIndicator {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FormSubmission]): FormSubmission | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketIntelligence]): MarketIntelligence | null {
    return value.length === 0 ? null : from_candid_MarketIntelligence_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TimerState]): TimerState | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    historicalAccuracy: number;
    asset: string;
    timeframe: string;
    overallSignal: _SignalConfidence;
    indicators: Array<_TechnicalIndicator>;
    timestamp: bigint;
}): {
    id: bigint;
    historicalAccuracy: number;
    asset: string;
    timeframe: string;
    overallSignal: SignalConfidence;
    indicators: Array<TechnicalIndicator>;
    timestamp: bigint;
} {
    return {
        id: value.id,
        historicalAccuracy: value.historicalAccuracy,
        asset: value.asset,
        timeframe: value.timeframe,
        overallSignal: from_candid_SignalConfidence_n22(_uploadFile, _downloadFile, value.overallSignal),
        indicators: from_candid_vec_n24(_uploadFile, _downloadFile, value.indicators),
        timestamp: value.timestamp
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: number;
    indicatorType: _IndicatorType;
    signal: _SignalConfidence;
}): {
    value: number;
    indicatorType: IndicatorType;
    signal: SignalConfidence;
} {
    return {
        value: value.value,
        indicatorType: from_candid_IndicatorType_n27(_uploadFile, _downloadFile, value.indicatorType),
        signal: from_candid_SignalConfidence_n22(_uploadFile, _downloadFile, value.signal)
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n31(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    strongBuy: null;
} | {
    sell: null;
} | {
    neutral: null;
} | {
    strongSell: null;
}): SignalConfidence {
    return "buy" in value ? SignalConfidence.buy : "strongBuy" in value ? SignalConfidence.strongBuy : "sell" in value ? SignalConfidence.sell : "neutral" in value ? SignalConfidence.neutral : "strongSell" in value ? SignalConfidence.strongSell : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fvg: null;
} | {
    rsi: null;
} | {
    macd: null;
} | {
    vwap: null;
} | {
    movingAverage: null;
} | {
    bollingerBands: null;
} | {
    orderBlocks: null;
}): IndicatorType {
    return "fvg" in value ? IndicatorType.fvg : "rsi" in value ? IndicatorType.rsi : "macd" in value ? IndicatorType.macd : "vwap" in value ? IndicatorType.vwap : "movingAverage" in value ? IndicatorType.movingAverage : "bollingerBands" in value ? IndicatorType.bollingerBands : "orderBlocks" in value ? IndicatorType.orderBlocks : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketIntelligence>): Array<MarketIntelligence> {
    return value.map((x)=>from_candid_MarketIntelligence_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TechnicalIndicator>): Array<TechnicalIndicator> {
    return value.map((x)=>from_candid_TechnicalIndicator_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n30(_uploadFile, _downloadFile, x));
}
function to_candid_IndicatorType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndicatorType): _IndicatorType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_SignalConfidence_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalConfidence): _SignalConfidence {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_TechnicalIndicator_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TechnicalIndicator): _TechnicalIndicator {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_TimerType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimerType): _TimerType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: number;
    indicatorType: IndicatorType;
    signal: SignalConfidence;
}): {
    value: number;
    indicatorType: _IndicatorType;
    signal: _SignalConfidence;
} {
    return {
        value: value.value,
        indicatorType: to_candid_IndicatorType_n15(_uploadFile, _downloadFile, value.indicatorType),
        signal: to_candid_SignalConfidence_n17(_uploadFile, _downloadFile, value.signal)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimerType): {
    presale: null;
} | {
    airdrop: null;
} {
    return value == TimerType.presale ? {
        presale: null
    } : value == TimerType.airdrop ? {
        airdrop: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IndicatorType): {
    fvg: null;
} | {
    rsi: null;
} | {
    macd: null;
} | {
    vwap: null;
} | {
    movingAverage: null;
} | {
    bollingerBands: null;
} | {
    orderBlocks: null;
} {
    return value == IndicatorType.fvg ? {
        fvg: null
    } : value == IndicatorType.rsi ? {
        rsi: null
    } : value == IndicatorType.macd ? {
        macd: null
    } : value == IndicatorType.vwap ? {
        vwap: null
    } : value == IndicatorType.movingAverage ? {
        movingAverage: null
    } : value == IndicatorType.bollingerBands ? {
        bollingerBands: null
    } : value == IndicatorType.orderBlocks ? {
        orderBlocks: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SignalConfidence): {
    buy: null;
} | {
    strongBuy: null;
} | {
    sell: null;
} | {
    neutral: null;
} | {
    strongSell: null;
} {
    return value == SignalConfidence.buy ? {
        buy: null
    } : value == SignalConfidence.strongBuy ? {
        strongBuy: null
    } : value == SignalConfidence.sell ? {
        sell: null
    } : value == SignalConfidence.neutral ? {
        neutral: null
    } : value == SignalConfidence.strongSell ? {
        strongSell: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<TechnicalIndicator>): Array<_TechnicalIndicator> {
    return value.map((x)=>to_candid_TechnicalIndicator_n13(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
